### PR TITLE
Removed history.js and encapsulate the java code

### PR DESCRIPTION
**Pull request by perryflynn**
I encapsulate the java script in a startup fucntion to ensure that all html code is ready.

Also i delete the history.js.
It brings no real time savings.

### CODE REVIEW

**Comment by TheInsomniac** [comment]
Why did you do a body onload instead of just keeping the script in the footer? Having the JS in the bottom of the <body> means that the DOM has already completed loading anyways. We're not loading the #items async so we have nothing to wait for...

As for the history.js, it's a bit superfluous but I like the speed with which pages change and the lack of window flash from a complete re-draw. The function is only executed if the browser supports the History API and is easily removed by commenting out the script in footer.html (as is why it's a separate file instead of just appended in a <script> tag.

I won't merge these commits as, I feel, they're a step backwards but look forward to any future enhancements that you might submit.

**Comment by perryflynn** [comment]
IMHO the startup function is easier to read. The java script code isn't spread all over the html source.

I dont have this "flash" in my browsers. 
Possibly this can happen with older PCs...

I also found a little bug: You must add a document.title update to the AJAX response processing in history.js. Currently you update only the breadcrumbs.

**Comment by TheInsomniac** [comment]
I understand regarding your mess of JavaScript comment. Having some in the body and some external is a little messy. My only reason for doing this was integrating the required items in the HTML and, what I consider, optional items in the external. I'll clean this up...

Truthfully the whole history api thing was just an exercise for me. I've never worked with it before and needed some project where I could use it :) Perhaps I should default to commenting out the import so users can enable it if they so choose?

Thanks for pointing out the lack of updating title for the ajax request. I'll fix shortly.

**Comment by perryflynn** [comment]
You could add a comment to the README and the footer.html. Also a loading indicator and error handling when the ajax request fails would be great.

Before I forget: Thanks for this cool design and your time. :)

**Comment by TheInsomniac** [comment]
and thank you for your suggestions and support!

**Pull request closed without merging**
